language: c
sudo: required
cache:
  timeout: 600
  directories:
  - /tmp/microchip
install:
- sudo $TRAVIS_BUILD_DIR/.ci/install.sh
- sudo $TRAVIS_BUILD_DIR/.ci/install-mplab.sh
- sudo $TRAVIS_BUILD_DIR/.ci/install-azure-cli.sh
script:
- pushd $TRAVIS_BUILD_DIR/firmware && ./generate_version_header.sh && ./fix_mplab.sh && ./compile.sh && ./generate_hex_with_checksum.sh && ./merge_bootloader.sh && popd
after_success:
- pushd $TRAVIS_BUILD_DIR/firmware && $TRAVIS_BUILD_DIR/.ci/upload-to-azure.sh && popd
